// 11pro models
var MODEL_LIST = {
    'MWC22KH/A': 'pro 64GB space gray',
    'MWC32KH/A': 'pro 64GB silver',
    'MWC62KH/A': 'pro 64GB midnightgreen',
    'MWC52KH/A': 'pro 64GB gold',
    'MWC72KH/A': 'pro 256GB space gray',
    'MWC82KH/A': 'pro 256GB silver',
    'MWCC2KH/A': 'pro 256GB midnightgreen',
    'MWC92KH/A': 'pro 256GB gold',
    'MWCD2KH/A': 'pro 512GB space gray',
    'MWCE2KH/A': 'pro 512GB silver',
    'MWCG2KH/A': 'pro 512GB midnightgreen',
    'MWCF2KH/A': 'pro 512GB gold',
    'MWHD2KH/A': 'max 64GB space gray',
    'MWHF2KH/A': 'max 64GB silver',
    'MWHH2KH/A': 'max 64GB midnightgreen',
    'MWHG2KH/A': 'max 64GB gold',
    'MWHJ2KH/A': 'max 256GB space gray',
    'MWHK2KH/A': 'max 256GB silver',
    'MWHM2KH/A': 'max 256GB midnightgreen',
    'MWHL2KH/A': 'max 256GB gold',
    'MWHN2KH/A': 'max 512GB space gray',
    'MWHP2KH/A': 'max 512GB silver',
    'MWHR2KH/A': 'max 512GB midnightgreen',
    'MWHQ2KH/A': 'max 512GB gold'
};